FROM gcr.io/distroless/static-debian12:nonroot@sha256:a9329520abc449e3b14d5bc3a6ffae065bdde0f02667fa10880c49b35c109fd1
WORKDIR /app
COPY --chown=nonroot:nonroot build/driver-service /app/driver-service
USER nonroot:nonroot
EXPOSE 9092
ENTRYPOINT ["/app/driver-service"]
