FROM gcr.io/distroless/static-debian12:nonroot@sha256:afa5c872c891853ca7fcf1f12c3edb23f7eeef36189728842dd51042ff57f7ab
WORKDIR /app
COPY --chown=nonroot:nonroot build/trip-service /app/trip-service
USER nonroot:nonroot
EXPOSE 9093
ENTRYPOINT ["/app/trip-service"]
