ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url   TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone        VARCHAR(30);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address      TEXT;
