FROM gcr.io/distroless/static-debian12:nonroot@sha256:a9329520abc449e3b14d5bc3a6ffae065bdde0f02667fa10880c49b35c109fd1
WORKDIR /app
COPY --chown=nonroot:nonroot build/payment-service /app/payment-service
COPY --chown=nonroot:nonroot services/payment-service/migrations /app/migrations
USER nonroot:nonroot
ENTRYPOINT ["/app/payment-service"]
