apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "e2e"
  APP_BASE_URL: "http://localhost:8081"

  GATEWAY_HTTP_ADDR:  ":8081"
  USER_HTTP_ADDR:     ":8082"
  TRIP_GRPC_ADDR:     ":9093"
  DRIVER_GRPC_ADDR:   ":9092"
  CHAT_HTTP_ADDR:     ":8084"

  TRIP_SERVICE_URL:   "trip-service:9093"
  DRIVER_SERVICE_URL: "driver-service:9092"
  USER_SERVICE_URL:   "http://user-service:8082"

  KAFKA_BROKERS:            "172.17.0.1:9092"
  KAFKA_SASL_MECHANISM:     ""
  KAFKA_REPLICATION_FACTOR: "1"

  OTEL_COLLECTOR_ENDPOINT: ""
  REDIS_URL:               "172.17.0.1:6379"

  PAYMENT_MODE:       "test"
  STRIPE_CURRENCY:    "eur"
  STRIPE_SUCCESS_URL: "http://localhost:8081/?payment=success"
  STRIPE_CANCEL_URL:  "http://localhost:8081/?payment=cancel"

  SERVICE_REFERER: "http://localhost:8081"

  SMTP_HOST: "localhost"
  SMTP_PORT: "587"

  USER_SERVICE_GRPC_URL: "user-service:9091"
  SCHEMA_REGISTRY_URL:   ""

  MIGRATIONS_PATH: "migrations"
  SEED: "true"
