---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          env:
            - name: KAFKA_TLS_CA_CERT
              value: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service
spec:
  template:
    spec:
      containers:
        - name: trip-service
          env:
            - name: KAFKA_TLS_CA_CERT
              value: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  template:
    spec:
      containers:
        - name: driver-service
          env:
            - name: KAFKA_TLS_CA_CERT
              value: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  template:
    spec:
      containers:
        - name: payment-service
          env:
            - name: KAFKA_TLS_CA_CERT
              value: ""
