apiVersion: v1
kind: Namespace
metadata:
  name: drova
  labels:
    app.kubernetes.io/name: drova
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: drova-quota
  namespace: drova
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "30"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: drova-limitrange
  namespace: drova
spec:
  limits:
    - type: Container
      default:
        cpu: 250m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "2"
        memory: 2Gi
