FROM gcr.io/distroless/static-debian12:nonroot@sha256:afa5c872c891853ca7fcf1f12c3edb23f7eeef36189728842dd51042ff57f7ab
WORKDIR /app
COPY --chown=nonroot:nonroot build/chat-service /app/chat-service
USER nonroot:nonroot
EXPOSE 8084
ENTRYPOINT ["/app/chat-service"]
