name: Dependency Review

on:
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/dependency-review.yaml'

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/dependency-review-action@67d4f4bd7a9b17a0db54d2a7519187c65e339de8 # v4.10.0
        with:
          fail-on-severity: high
          comment-summary-in-pr: always
